(in-package :mu-cl-resources)

(add-prefix "nfo" "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#")
(add-prefix "nie" "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#")
(add-prefix "dct" "http://purl.org/dc/terms/")
(add-prefix "dbpedia" "http://dbpedia.org/ontology/")
(add-prefix "cogs" "http://vocab.deri.ie/cogs#")
(add-prefix "adms" "http://www.w3.org/ns/adms#")
(add-prefix "task" "http://redpencil.data.gift/vocabularies/tasks/")
(add-prefix "skos" "http://www.w3.org/2004/02/skos/core#")
(add-prefix "oslc" "http://open-services.net/ns/core#")
(add-prefix "nfo" "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#")
(add-prefix "rpioHttp" "http://redpencil.data.gift/vocabularies/http/")
(add-prefix "dgftSec" "http://lblod.data.gift/vocabularies/security/")
(add-prefix "meb" "http://rdf.myexperiment.org/ontologies/base/")
(add-prefix "muAccount" "http://mu.semte.ch/vocabularies/account/")
(add-prefix "dgftOauth" "http://kanselarij.vo.data.gift/vocabularies/oauth-2.0-session/")
(add-prefix "wotSec" "https://www.w3.org/2019/wot/security#")
(add-prefix "schema" "http://schema.org/")
(add-prefix "hrvst" "http://lblod.data.gift/vocabularies/harvesting/")
(add-prefix "dgftSec" "http://lblod.data.gift/vocabularies/security/")
